site_name: HeatSuite Docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  features:
    - navigation.tabs 
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
    - announce.dismiss
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home : 
    - index.md
    - Research Using HeatSuite: research.md
  - Watch Application:
    - Watch Setup: watchapp/index.md 
    - EMA Survey: watchapp/watchapp-ema.md
    - Tasks: watchapp/watchapp-tasks.md
    - HeatSuite Module: watchapp/watchapp-hsmodule.md
  - Environmental Nodes:
    - Introduction: nodes/index.md
    - Primary Node Assembly: nodes/node-primary-build.md


plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:      
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/nravanelli"  target="_blank" rel="noopener">Nicholas Ravanelli</a>
